/**
 * The sentence, tested as the artifact it is.
 *
 * Design is 25% of this hackathon's score and for a voice device the interaction
 * model IS the sentence. It used to be a string literal in three unconnected files
 * — three wordings of the one thing the product is named for, generated by nothing
 * and asserted by no test. These are the properties that make it a retraction
 * rather than a restatement, in the order a frightened listener hears them.
 */
import { describe, expect, it } from 'vitest'

import { GLOSSARY, glossesFor, renderRetraction, spokenAge } from '../src/retraction.ts'
import { DEMO_NOW, RAY, STAGED_REVISION, seedDemo } from '../src/seed.ts'
import { uriFor } from '../src/store.ts'
import type { CareRecord } from '../src/types.ts'

// The staged revision, applied — this is the moment the product exists for: v2 was
// already spoken and v3 arrives under the sentence.
const store = seedDemo()
store.publish({ ...STAGED_REVISION, writtenAt: DEMO_NOW.toISOString() })
const chain = store.versions(RAY, 'weight_bearing')
const prev = chain.at(-2)!
const next = chain.at(-1)!
const later = new Date(DEMO_NOW.getTime() + 30_000)

const sentence = () => renderRetraction(prev, next, { now: later })

describe('the retraction withdraws before it explains', () => {
  it('opens with the stop, not with the metadata', () => {
    // The regression: "That changed thirty seconds ago. Sarah's moved you to…"
    // leads with a timestamp and buries the instruction a person acts on first.
    const s = sentence()
    expect(s.startsWith('Wait — don’t do that.')).toBe(true)
    expect(s.indexOf('out of date')).toBeLessThan(s.indexOf('changed it'))
  })

  it('names the sentence being withdrawn, so there is one instruction to drop', () => {
    expect(sentence()).toContain(prev.value.replace(/\.$/, ''))
  })

  it('names the new value, its author and its age', () => {
    const s = sentence()
    expect(s).toContain(next.value.replace(/\.$/, ''))
    expect(s).toContain(next.authorLabel)
    expect(s).toContain('30 seconds ago')
  })

  it('is built from record fields — a different author changes the sentence', () => {
    const other: CareRecord = { ...next, authorLabel: 'Dr Mensah, GP' }
    expect(renderRetraction(prev, other, { now: later })).toContain('Dr Mensah, GP')
    expect(renderRetraction(prev, other, { now: later })).not.toContain(next.authorLabel)
  })
})

describe('the retraction leaves no clinical term unglossed', () => {
  it('glosses every jargon phrase the new value contains', () => {
    const s = sentence()
    for (const { label, gloss } of glossesFor(next.value)) {
      expect(s, label).toContain(gloss)
    }
    // The seeded revision really does contain one, or this test proves nothing.
    expect(glossesFor(next.value).length).toBeGreaterThan(0)
  })

  it('adds no guidance of its own — every gloss restates the clinician', () => {
    // Unsay "generates no clinical guidance" (README, SPEC, web/index.html). A gloss
    // that told the patient what to DO would falsify that on the product's own page.
    for (const { gloss } of GLOSSARY) {
      expect(gloss).not.toMatch(/\byou should\b|\bmake sure\b|\bcall\b|\bstop taking\b|\bavoid\b/i)
    }
  })

  it('says nothing about jargon that is not in the value', () => {
    expect(sentence()).not.toContain('the blood-thinning tablet')
  })
})

describe('spoken ages are ages a person would say out loud', () => {
  it('collapses the first ten seconds to "just now"', () => {
    expect(spokenAge(0)).toBe('just now')
    expect(spokenAge(9_000)).toBe('just now')
  })

  it('never speaks a negative age', () => {
    // A server whose store was seeded on one clock and read on another produced
    // "-32d ago" for every record. Clamped here as well as fixed at the source.
    expect(spokenAge(-86_400_000)).toBe('just now')
  })

  it('scales to minutes, hours and days', () => {
    expect(spokenAge(90_000)).toBe('2 minutes ago')
    expect(spokenAge(3_600_000)).toBe('an hour ago')
    expect(spokenAge(3 * 86_400_000)).toBe('3 days ago')
  })
})

describe('the server hands the sentence to the host', () => {
  it('carries unsay/retraction and the previous value on a read of a revised resource', () => {
    // Asserted through the store the server reads, so the fields exist for the
    // handler to attach; scripts/e2e.ts asserts they survive the wire.
    const uri = uriFor(RAY, 'weight_bearing', 'user')
    expect(store.read(uri, { sub: 't', scopes: ['care.read.user'] }).version).toBe(3)
    expect(prev.version).toBe(2)
    expect(renderRetraction(prev, next).length).toBeGreaterThan(80)
  })
})

/** a2a r01: the gloss is worded as an instruction, so it must never gloss a prohibition. */
describe('gloss fails safe on a qualified instruction', () => {
  it('does not gloss a negated instruction', () => {
    expect(glossesFor('Do NOT progress to full weight-bearing as tolerated until the X-ray is reviewed.')).toEqual([])
  })
  it('does not gloss a conditional progression across two levels', () => {
    expect(glossesFor('Stay partial weight-bearing until review, then full weight-bearing as tolerated.')).toEqual([])
    expect(glossesFor('Partial weight-bearing this week; full weight-bearing as tolerated next week.')).toEqual([])
  })
  it('still glosses the staged revision', () => {
    expect(glossesFor('Full weight-bearing as tolerated.').map((g) => g.label)).toEqual([
      'full weight-bearing as tolerated',
    ])
  })
})

describe('renderRetraction refuses never-speak content', () => {
  it('throws on an assistant-audience record', () => {
    const base = {
      subject: 'ray',
      topic: 'risk',
      version: 1,
      value: 'Fall risk: HIGH.',
      authorId: 'a',
      authorLabel: 'A',
      writtenAt: '2026-10-08T09:00:00Z',
      prevHash: null,
      versionHash: 'x',
    }
    const prev = { ...base, audience: 'assistant' as const }
    const next = { ...base, version: 2, value: 'Fall risk: LOW.', audience: 'assistant' as const }
    expect(() => renderRetraction(prev as never, next as never)).toThrow(/assistant-audience/)
  })
})
