/**
 * The sentence the product is named for.
 *
 * "Unsay" is a retraction, and a retraction is a piece of COPY before it is a
 * piece of protocol. Until this file existed the sentence was a string literal in
 * DEMO.md, in web/index.html and in scripts/e2e.ts — three wordings of the one
 * artifact the whole submission is about, generated by nothing and asserted by no
 * test. LESSONS R10: an unexercised seam is a missing feature, and copy nobody
 * can regression-test is copy that drifts.
 *
 * It is rendered server-side and handed to the host on `_meta['unsay/retraction']`
 * of a `resources/read` that follows a revision, so a host that wants the wording
 * does not have to invent it. Whether the host says it is the host's decision
 * (SPEC T-2, FRICTION F-003); we can only make the right words available.
 *
 * Three rules the wording obeys, in this order, because a frightened 68-year-old
 * mid-transfer hears the first clause and acts on it:
 *
 *   1. WITHDRAW FIRST. The safety-critical instruction — stop doing the thing —
 *      comes before any metadata. "That changed thirty seconds ago" leads with a
 *      timestamp and buries the stop.
 *   2. NAME WHAT IS BEING WITHDRAWN. Without the superseded sentence the listener
 *      is left holding two contradictory instructions and no marker for which to
 *      drop. This is why `whats_changed` and the read `_meta` carry the previous
 *      value at all.
 *   3. GLOSS THE JARGON. A care record is written clinician-to-clinician.
 *      "Full weight-bearing as tolerated" is not a sentence a patient can act on,
 *      and the gloss is a translation of the clinician's words — never advice of
 *      our own, which is the line SPEC's "What Unsay does not claim" draws.
 */
import type { CareRecord } from './types.ts'

/**
 * Clinician-to-clinician phrases that appear in the seeded care plan, each with a
 * plain-English restatement of the SAME instruction. Nothing here adds guidance:
 * every gloss is a paraphrase of the clinician's own sentence, which is why the
 * table is small, closed, and lives next to the test that reads it.
 */
export const GLOSSARY: readonly { term: RegExp; label: string; gloss: string }[] = [
  {
    term: /full weight[- ]bearing as tolerated/i,
    label: 'full weight-bearing as tolerated',
    gloss: 'you can put as much weight through that leg as is comfortable',
  },
  {
    term: /partial weight[- ]bearing/i,
    label: 'partial weight-bearing',
    gloss: 'only some of your weight goes through that leg',
  },
  {
    term: /non[- ]weight[- ]bearing|no weight through/i,
    label: 'non-weight-bearing',
    gloss: 'no weight at all goes through that leg',
  },
  {
    term: /hip flexion/i,
    label: 'hip flexion',
    gloss: 'bending at the hip',
  },
  {
    term: /rivaroxaban/i,
    label: 'rivaroxaban',
    gloss: 'the blood-thinning tablet',
  },
]

/**
 * Ages a host can say out loud. Deliberately coarse: "34 seconds" is a precision a
 * spoken sentence cannot carry and a listener does not need, and the word "just
 * now" is what a person actually says about a change they watched arrive.
 */
export function spokenAge(ms: number): string {
  const s = Math.max(0, Math.round(ms / 1000))
  if (s < 10) return 'just now'
  if (s < 60) return `${s} seconds ago`
  const m = Math.round(s / 60)
  if (m < 60) return m === 1 ? 'a minute ago' : `${m} minutes ago`
  const h = Math.round(m / 60)
  if (h < 36) return h === 1 ? 'an hour ago' : `${h} hours ago`
  const d = Math.round(h / 24)
  return d === 1 ? 'yesterday' : `${d} days ago`
}

/** Every glossed term present in `text`, in the order the table declares them. */
export function glossesFor(text: string): { label: string; gloss: string }[] {
  return GLOSSARY.filter((g) => g.term.test(text)).map(({ label, gloss }) => ({ label, gloss }))
}

const quote = (s: string) => `“${s.replace(/\s+$/, '').replace(/\.$/, '')}.”`

export interface RetractionOptions {
  /** Defaults to `next.writtenAt`, which is the server clock at the moment of the write. */
  now?: Date
}

/**
 * The spoken retraction for a fact that changed under an answer already in flight.
 *
 * Built from record fields only — no branch here can invent a value, an author or
 * an age that is not in the chain. `prev` is the version the host already read
 * aloud; `next` is the version that superseded it.
 */
export function renderRetraction(
  prev: CareRecord,
  next: CareRecord,
  opts: RetractionOptions = {},
): string {
  const now = opts.now ?? new Date(next.writtenAt)
  const age = spokenAge(now.getTime() - new Date(next.writtenAt).getTime())
  const glosses = glossesFor(next.value)

  const parts = [
    // 1 — the stop, before anything else.
    `Wait — don’t do that. What I just told you is out of date.`,
    // 2 — the sentence being withdrawn, so there is one instruction to drop.
    `I said ${quote(prev.value)}`,
    // …and the one that replaces it, with who changed it and when.
    `${next.authorLabel} changed it ${age}: ${quote(next.value)}`,
  ]

  // 3 — the gloss, marked as a restatement of the clinician's words.
  if (glosses.length) {
    parts.push(
      `In plain terms, ${glosses.map((g) => `${g.label} means ${g.gloss}`).join(', and ')}.`,
    )
  }

  return parts.join(' ')
}
